server:
  port: 9901

spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
    enabled: false

  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
      auto-index-creation: true


  security:
#    user:
#      name: user
#      password: 1234

    oauth2:
      client:
        registration:
          kakao:
           

          naver:
           

          google:
           

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize    #카카오 login Page
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   #naver login Page
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  jwt:
    secretKey: 12345-12345-12345-123345
    ACCESS_TOKEN_EXPIRE_TIME: 1800000    # 1000 * 60 * 30   30분
    REFRESH_TOKEN_EXPIRE_TIME: 3600000   # 1000 * 60 * 60   60분

#?? ????
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
