server:
  port: 9901

spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888   #Config server
    enabled: true

  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
      auto-index-creation: true


  security:
#    user:
#      name: user
#      password: 1234

    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: 182aa593d6c9dd9a5ab2c20104a1ce9b
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            redirect-uri: "http://localhost:80/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

          naver:
            client-name: Naver
            client-id: UE2XIVBkw89rDhSDbSe4
            client-secret: sJkHASTjKZ
#            redirect-uri: "http://localhost:80/{action}/oauth2/code/{registrationId}"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"          # (== http://localhost:80/login/oauth2/code/naver) 게이트에이 하드코딩방식
            authorization-grant-type: authorization_code
            scope: name, email

          google:
            client-name: google
            client-id: 129842654485-c84i13kt2mj4kghbq25kbn4t2kdjh97b.apps.googleusercontent.com
            client-secret: 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
            #default http://localhost:8080/login/oauth2/code/google
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

        provider:
          kakao:
            #여기를 lb://API-GATEWAY
            authorization-uri: https://kauth.kakao.com/oauth/authorize    #카카오 login Page

            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   #naver login Page
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  jwt:
    secretKey: 239192-3999-01002-39123
    ACCESS_TOKEN_EXPIRE_TIME: 1800000    # 1000 * 60 * 30   30분
    REFRESH_TOKEN_EXPIRE_TIME: 3600000   # 1000 * 60 * 60   60분

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

